Source/Web/BirthdaySystem.Web/ViewModels/Vote/CreateNewVoteModel.cs
namespace BirthdaySystem.Web.ViewModels.Vote
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    using AutoMapper;

    using BirthdaySystem.Models;
    using BirthdaySystem.Web.Infrastructure.Mapping;
    using BirthdaySystem.Web.Infrastructure.Populators;

    public class CreateNewVoteModel : IMapFrom<Vote>
    {
        // http://nimblegecko.com/using-simple-drop-down-lists-in-ASP-NET-MVC/
        [Required]
        [Display(Name = "Birthday vote for")]
        public string BirthdayPerson { get; set; }

        public IEnumerable<SelectListItem> BirthdayPeople { get; set; }

        [Required]
        [Display(Name = "Vote Start Date")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [Display(Name = "Vote End Date")]
        [DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

        [Required]
        [Display(Name = "Year")]
        public int Year { get; set; }

        public void CreateMappings(IConfiguration configuration)
        {
            configuration.CreateMap<Vote, CreateNewVoteModel>()
                .ForMember(p => p.BirthdayPerson, opt => opt.MapFrom(p => p.BirthdayPerson.FirstName))
                .ReverseMap();
        }
    }
}

Source/Web/BirthdaySystem.Web/ViewModels/Vote/PresentVoteModel.cs
namespace BirthdaySystem.Web.ViewModels.Vote
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    using System.Web.Mvc;

    using BirthdaySystem.Models;
    using BirthdaySystem.Web.Infrastructure.Mapping;
    
    public class PresentVoteModel : IMapFrom<PresentVote>
    {
        public int VoteId { get; set; }

        public string UserId { get; set; }

        [Display(Name = "Present")]
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Choose a present from the list")]
        public int PresentId { get; set; }

        //[Display(Name = "Present")]
        //[Required]
        //public string Present { get; set; }

        //public IEnumerable<SelectListItem> Presents { get; set; }

        public DateTime DateVote { get; set; }

        [Display(Name = "Birthday for")]
        public string BirthdayPerson { get; set; }
    }
}

Source/Web/BirthdaySystem.Web/Controllers/VoteController.cs
namespace BirthdaySystem.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using Microsoft.AspNet.Identity;

    using BirthdaySystem.Data.Common.Data;
    using BirthdaySystem.Data.Common.Services.Contracts;
    using BirthdaySystem.Web.Infrastructure.Populators;
    using BirthdaySystem.Web.ViewModels.Vote;
    using BirthdaySystem.Models;
    using BirthdaySystem.Web.ViewModels.Home;

    public class VoteController : Controller
    {
        private IBirthdayPeopleService birthdayData;
        private IVoteService voteData;
        private IPresentService presentData;
        private readonly IBirthdayData dbData;

        public VoteController(IBirthdayPeopleService birthdayPeople, IVoteService voteData, IPresentService presentData, IBirthdayData dbData)
        {
            this.birthdayData = birthdayPeople;
            this.voteData = voteData;
            this.presentData = presentData;
            this.dbData = dbData;
        }

        [HttpGet]
        [Authorize]
        //[ValidateAntiForgeryToken]
        // GET: Vote
        public ActionResult CreateVote()
        {
            // http://stackoverflow.com/questions/18448637/how-to-get-current-user-and-how-to-use-user-class-in-mvc5
            var birtdayPeople = this.birthdayData
                .GetAllBirthdayPeople(this.User.Identity.GetUserId())
                .ToList();

            var model = new CreateNewVoteModel();

            model.BirthdayPeople = new SelectList(birtdayPeople, "Id", "Name");

            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult CreateVote(CreateNewVoteModel input)
        {
            var birtdayPeople = this.birthdayData
                .GetAllBirthdayPeople(this.User.Identity.GetUserId())
                .ToList();

            input.BirthdayPeople = new SelectList(birtdayPeople, "Id", "Name");

            if (ModelState.IsValid)
            {
                var currentUser = this.User.Identity.GetUserId();
                if (input.BirthdayPerson == currentUser)
                {
                    throw new InvalidOperationException("It is allowed to start a new vote for the other people only!");
                }

                var voteExist = this.voteData.GetVote(input.BirthdayPerson, input.Year).FirstOrDefault();

                if (voteExist != null)
                {
                    //throw new InvalidOperationException("There is a vote for this user and year!");
                    return View("Error");
                }

                var birthdayPerson = this.birthdayData.GetUser(input.BirthdayPerson).FirstOrDefault();
                var initiator = this.birthdayData.GetUser(currentUser).FirstOrDefault();

                var vote = new Vote
                {
                    BirthdayPersonId = birthdayPerson.Id,
                    //BirthdayPerson = birthdayPerson,
                    InitiatorId = currentUser,
                    //Initiator = initiator,
                    StartDate = input.StartDate,
                    EndDate = input.EndDate,
                    Year = input.Year
                };

                this.dbData.Votes.Add(vote);
                this.dbData.Votes.SaveChanges();

                return this.RedirectToAction("OpenedVotes");
            }

            return View(input);
        }

        [HttpGet]
        [Authorize]
        public ActionResult OpenedVotes()
        {
            var availableVotes = this.voteData
                .GetAvailableVotes(this.dbData, this.User.Identity.GetUserId())
                .ProjectTo<VoteModel>()
                .ToList();

            return View(availableVotes);
        }

        [HttpGet]
        [Authorize]
        [PopulatePresents]
        public ActionResult PresentVote(int id, string birthdayPersonName)
        {
            var presentVateModel = new PresentVoteModel
            {
                VoteId = id,
                BirthdayPerson = birthdayPersonName,
            };

            return View(presentVateModel);
        }


        [HttpPost]
        [Authorize]
        [PopulatePresents]
        [ValidateAntiForgeryToken]
        // http://www.codeproject.com/Articles/758458/Passing-Data-View-to-Controller-Controller-to-View
        // TODO : Do dripdown list with cashed data from ViewBag!!!
        public ActionResult PresentVote(PresentVoteModel input, FormCollection formCollection)
        {
            //formCollection.Get("YearTo")
            if (!string.IsNullOrEmpty(formCollection.Get("PresentsId")))
            {
                var presentVote = new PresentVote
                {
                    VoteId = input.VoteId,
                    UserId = this.User.Identity.GetUserId(),
                    PresentId = int.Parse(formCollection.Get("PresentsId")),
                    DateVote = DateTime.Now
                };

                this.dbData.PresentsVotes.Add(presentVote);
                this.dbData.Votes.SaveChanges();

                return this.RedirectToAction("OpenedVotes");
            }
            
            return View(input);
        }


        /*
         * 
        [HttpGet]
        [Authorize]
        [PopulatePresents]
        public ActionResult PresentVote(int id, string birthdayPersonName)
        {
            //var model = new PresentVoteModel();
            var presentVateModel = new PresentVoteModel
            {
                VoteId = id,
                // UserId = this.User.Identity.GetUserId(),
                BirthdayPerson = birthdayPersonName,
                // DateVote = DateTime.Now,
            };

            var presents = this.presentData.GetAllPresents().ToList();

            presentVateModel.Presents = new SelectList(presents, "Id", "Name"); ;

            return View(presentVateModel);
        }
         * 
         * 
         * 
        [HttpPost]
        [Authorize]
        [PopulatePresents]
        [ValidateAntiForgeryToken]
        // http://www.codeproject.com/Articles/758458/Passing-Data-View-to-Controller-Controller-to-View
        // TODO : Do dripdown list with cashed data from ViewBag!!!
        public ActionResult PresentVote(PresentVoteModel input) // , FormCollection presentsDropdown) //
        {
            var presents = this.presentData.GetAllPresents().ToList();

            input.Presents = new SelectList(presents, "Id", "Name"); ;

            if (ModelState.IsValid)
            {
                var presentVote = new PresentVote
                {
                    VoteId = input.VoteId,
                    UserId = this.User.Identity.GetUserId(),
                    PresentId = input.PresentId, //int.Parse(input.Present),
                    DateVote = DateTime.Now
                };

                this.dbData.PresentsVotes.Add(presentVote);
                this.dbData.Votes.SaveChanges();

                return this.RedirectToAction("OpenedVotes");
            }

            return View(input);
        }
        */
            

        //[HttpGet]
        [Authorize]
        public ActionResult CloseVote()
        {
            var votesForClosingByTheUser = this.voteData
                .GetAllUnclosedVotes(this.User.Identity.GetUserId())
                .Project()
                .To<VoteModel>()
                .ToList();

            return View(votesForClosingByTheUser);
        }

        //[HttpPost]
        [Authorize]
        public ActionResult CloseVoteById(int id)
        {
            this.voteData.CloseVote(id);

            //var votesForClosingByTheUser = this.voteData
            //    .GetAllUnclosedVotes(this.User.Identity.GetUserId())
            //    .Project()
            //    .To<VoteModel>()
            //    .ToList();

            //return View(votesForClosingByTheUser);

            return this.RedirectToAction("CloseVote");
        }
    }
}

Source/Web/BirthdaySystem.Web/Views/Vote/CloseVote.cshtml
@model IEnumerable<BirthdaySystem.Web.ViewModels.Home.VoteModel>
@{
    ViewBag.Title = "Votes opened by the user";
}

<h2>@ViewBag.Title</h2>

<table class="table-bordered">
    <tr class="text-center text-primary">
        <th class="col-md-4">Birthday for</th>
        <th class="col-md-1">Vote Start Date</th>
        <th class="col-md-1">Year</th>
    </tr>
    @foreach (var vote in Model)
    {
        <tr class="text-center">
            <td>@vote.BirthdayPerson.FirstName @vote.BirthdayPerson.LastName</td>
            <td>@vote.StartDate.ToShortDateString()</td>
            <td>@vote.Year</td>
            <td>@Html.ActionLink("Close me", "CloseVoteById", new { id = @vote.Id })</td>
        </tr>
    }
</table>

Source/Web/BirthdaySystem.Web/Views/Vote/CreateVote.cshtml
@model BirthdaySystem.Web.ViewModels.Vote.CreateNewVoteModel
@{
    ViewBag.Title = "Create a New Vote";
}

<h2>@ViewBag.Title</h2>

<div class="container">
    <div class="row">
        @using (Html.BeginForm("CreateVote", "Vote", FormMethod.Post))
        {
            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()

            <div class="row">
                @Html.LabelFor(m => m.BirthdayPerson)
                @Html.DropDownListFor(m=>m.BirthdayPerson, Model.BirthdayPeople as SelectList, "--Choose a Birthday Person--", new { style = "width: 600px;", @class = "form-control" })
                @*@Html.DropDownList("BirthdayPeopleId", ViewBag.BirthdayPeopleId as SelectList, "--Choose a Birthday Person--", new { style = "width: 600px;", @class = "form-control" })*@
                @Html.ValidationMessageFor(m => m.BirthdayPerson)
            </div>
            <div class="row">
                @Html.LabelFor(m => m.Year)
                @Html.TextBoxFor(m => m.Year, new { @class = "form-control", @Value = DateTime.Now.Year })
                @Html.ValidationMessageFor(m => m.Year)
            </div>
            <div class="row">
                @Html.LabelFor(m => m.StartDate)
                @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control", @Value = DateTime.Now.ToShortDateString() })
                @Html.ValidationMessageFor(m => m.StartDate)
            </div>
            @*<div class="row">
                @Html.LabelFor(m => m.EndDate)
                @Html.TextBoxFor(m => m.EndDate, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.EndDate)
            </div>*@
            <div class="row">
                <input type="submit" value="Start Vote" class="btn" />
                @Html.ActionLink("Back", "Index", "Home", null, new { @class = "btn-block btn-toolbar" })
                @*<div class="btn-block btn-toolbar">
                    @Html.ActionLink("Back", "Index")
                </div>*@
            </div>
        }
    </div>
</div>

Source/Web/BirthdaySystem.Web/Views/Vote/OpenedVotes.cshtml
@model IEnumerable<BirthdaySystem.Web.ViewModels.Home.VoteModel>
@{
    ViewBag.Title = "Available Opened Votes for Voting";
}

<h2>@ViewBag.Title</h2>

<table class="table-bordered">
    <tr class="text-center text-primary">
        <th class="col-md-4">Birthday for</th>
        <th class="col-md-1">Vote Start Date</th>
        <th class="col-md-1">Year</th>
        <th class="col-md-1"></th>
    </tr>
    @foreach (var vote in Model)
    {
        <tr class="text-center">
            <td>@vote.BirthdayPerson.FirstName @vote.BirthdayPerson.LastName</td>
            <td>@vote.StartDate.ToShortDateString()</td>
            <td>@vote.Year</td>
            <td>@Html.ActionLink("Vote for a present", "PresentVote", new { id = @vote.Id, birthdayPersonName = @vote.BirthdayPerson.Name })</td>
        </tr>
    }
</table>

Source/Web/BirthdaySystem.Web/Views/Vote/PresentVote.cshtml
@model BirthdaySystem.Web.ViewModels.Vote.PresentVoteModel
@{
    ViewBag.Title = "Give your vote for a present";
}

<h2>@ViewBag.Title</h2>

<div class="container">
    <div class="row">
        @using (Html.BeginForm("PresentVote", "Vote", FormMethod.Post))
        {
            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()

            @Html.HiddenFor(m => m.VoteId)

            <div class="row">
                @Html.LabelFor(m => m.BirthdayPerson)
                @Html.TextBoxFor(m => m.BirthdayPerson, new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div class="row">
                @Html.LabelFor(m => m.PresentId)
                @Html.DropDownList("PresentsId", ViewBag.PresentsId as SelectList, "--Choose a Present--", new { style = "width: 600px;", @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PresentId)
            </div>

            @*@Html.HiddenFor(m => m.VoteId)

                <div class="row">
                    @Html.LabelFor(m => m.BirthdayPerson)
                    @Html.TextBoxFor(m => m.BirthdayPerson, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="row">
                    @Html.LabelFor(m => m.PresentId)
                    @Html.DropDownListFor(m => m.PresentId, Model.Presents as SelectList, "--Choose a Present--", new { style = "width: 600px;", @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.PresentId)
                </div>*@
            <div class="row">
                <input type="submit" value="Vote" class="btn" />
                @Html.ActionLink("Back", "OpenedVotes", "Vote", null, new { @class = "btn-block btn-toolbar" })
            </div>
        }
    </div>
</div>